OUTDIR = r:\winbinder-dev\phpcode\wbdev_movable\obj 
LIBDIR = r:\winbinder-dev\phpcode\wbdev_movable\WinbinderComp\csource\php-5.1.2 
DLLDIR = r:\winbinder-dev\phpcode\wbdev_movable\WinbinderComp\binaries\php-5.1.2\ext 
SRCDIR = M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\ 
INCDIR = r:\winbinder-dev\phpcode\wbdev_movable\MSVC-util\inc\ 
MSLIB = r:\winbinder-dev\phpcode\wbdev_movable\MSVC-util\lib\ 
RCFILE = M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb.rc 
cc = cl 
rc = rc 
link = link 


SOURCES = 	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_bitmap.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_control.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_control_listview.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_control_menu.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_control_toolbar.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_control_treeview.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_draw.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_export.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_font.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_generic.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_lowlevel.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_sysdlg.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_wb_lib.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_window.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\phpwb_winsys.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_bitmap.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control_calendar.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control_html.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control_hyperlink.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control_listview.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control_menu.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control_tab.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control_toolbar.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_control_treeview.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_draw.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_font.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_generic.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_lowlevel.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_sysdlg.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_window.c	\
	M:\source-@14e7d89efd245fc6d095adb8e88e7685\core\wb\wb_winsys.c

OBJS = 	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_bitmap.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_control.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_control_listview.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_control_menu.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_control_toolbar.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_control_treeview.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_draw.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_export.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_font.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_generic.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_lowlevel.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_sysdlg.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_wb_lib.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_window.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\phpwb_winsys.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_bitmap.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control_calendar.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control_html.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control_hyperlink.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control_listview.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control_menu.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control_tab.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control_toolbar.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_control_treeview.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_draw.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_font.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_generic.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_lowlevel.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_sysdlg.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_window.obj	\
	r:\winbinder-dev\phpcode\wbdev_movable\obj\wb_winsys.obj

LIBS = 	\
	user32.lib	\
	gdi32.lib	\
	comdlg32.lib	\
	comctl32.lib	\
	shell32.lib	\
	ole32.lib 	\
	oleaut32.lib	\
	winmm.lib	\
	advapi32.lib	\
	r:\winbinder-dev\phpcode\wbdev_movable\WinbinderComp\csource\php-5.1.2\php-5.1.2ts.lib

all: $(DLLDIR)\php_winbinder.dll

$(OBJS): $(SOURCES)
	$(cc) /nologo /MT /W3 /GX /O2 /YX /FD /c /QIfist \
	/D "NDEBUG" /D ZEND_DEBUG=0 /D "WIN32" /D "_WINDOWS" /D "_MBCS" /D "_USRDLL" /D HAVE_WIN32STD=1 \
	/I "$(LIBDIR)" /I "$(INCDIR)\" /I "$(LIBDIR)\main" /I "$(LIBDIR)\Zend" /I "$(LIBDIR)\win32" /I "$(LIBDIR)\TSRM" /I "$(LIBDIR)\ext\standard" \
	/Fo"$(OUTDIR)\\" /Fd"$(OUTDIR)\\" $(SOURCES)

$(OUTDIR)\php_winbinder.dll.res: $(RCFILE)

$(DLLDIR)\php_winbinder.dll: $(OBJS)
	$(rc) /r /fo $(OUTDIR)\php_winbinder.dll.res /i "$(SRCDIR)\" /d $(FD) /d FILE_NAME="\"php_winbinder.dll\"" /d $(PN) /d $(PV) $(RCFILE)

	$(link) /nologo /dll /machine:I386 -out:$(DLLDIR)\php_winbinder.dll \
	$(OBJS) $(LIBS) $(OUTDIR)\php_winbinder.dll.res

#clean temporary files:
	del /q $(OUTDIR)\ *.pch $(DLLDIR)\php_winbinder.exp $(DLLDIR)\php_winbinder.lib